name: Create Markdowns
on: [push]
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Run script
        run: |
          python create_markdowns.py 
          git add .
          git commit -m "automatic markdowns generated"
          git push
